# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Studio 2016–18
email: john@thedesignoffice.org
description: Website for Design Studio, a required course in RISD Graphic Design
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ds1618.risd.gd" # the base hostname & protocol for your site
twitter_username:
github_username: risd-gd

# Build settings
markdown: kramdown
page_width: "8.5in"
page_height: "11in"
num_pages: 100
<<<<<<< HEAD
content_types: [1, 2, 3, 4, 5, etc]
=======
content_types: ["conversation", image, text, other] # note that if you have a multi-word content type to wrap it in quotes. This is not necessary in your post files, however.
>>>>>>> thedesignoffice/master
